### ISSUE TITLE
Klipse live REPL

### ISSUE THREAD

**Issue by dijonkitchen** [adityaathalye/clojure-by-example#7]
Maybe consider using https://github.com/viebel/klipse for faster feedback right on the same page instead of repl.it or static, pre-formatted text?

Might help let people play around with the code and see how it works.

**Comment by adityaathalye** [comment]
Thank you for the suggestion.

There are a few considerations for the choice of development environment:

0. This workshop targets practicing programmers, and not complete beginners. Our opinion is that getting started with standard developer tooling is part of the learning. We don't want to recommend Emacs (most of us use Emacs), because tha't too alien for most people. So far, Intellij + Cursive has been a rock-solid, if heavy to set up, option.

1. High quality developer tooling is crucial for a good learning experience --- static checks, linting, paredit/parinfer support, super-fast feedback etc. help immensely. The standard developer tooling sees heavy investment in imporving these creature comforts. The workshop participants also expect tools of the quality they are accustomed to in their normal day to day work.

2. Avoid Internet connectivity when teaching in-person --- this is a failure mode / source of degraded experience we wish to avoid when time is of the essence. We are able to avoid it, with a combination of project-local .m2, which we can share via USB stick, and previously configured local dev setup. 

3. Set up for future success. We hope programmers would want to keep going after the workshop, and start hobby projects. Having a local dev environment already set up removes the friction of having to switch tools / interaction models.

4. Maintainig support for multiple dev environments is overhead we can't take. Currently, we test the flow of the workshop on (Mac, Linux, Windows) x (1 IDE) x (1 local JVM). We don't have the bandwidth to ensure the learning experience is reliable on more platforms. If we choose an online dev tool, we also have to worry about browser compatibility issues and the necessarily sandboxed / opaque runtime of the online service.

**Comment by dijonkitchen** [comment]
Thanks so much for that detail @adityaathalye . What I meant was for the page on https://kimh.github.io/clojure-by-example/#hello-world though to have editable and evaluatable code on the page.

**Comment by adityaathalye** [comment]
Kim put a fair amount of work behind their project, to make it as nice as
they have. We just don't have the bandwidth, or intention, to do something
similar.

We MIT licensed the material so people would be free to use it, including,
to format it for their needs. If you choose to host a live version of the
material, we will be more than happy to cross-link to it.

For our purpose, the presentation and format is unlikely to change anytime
soon. Thus, I will close this issue.

Thanks once more for writing. Cheers!

**Comment by adityaathalye** [comment]
@dijonkitchen FYI: your input has been simmering in the back-burner.

Recently, I've been considering turning the workshop into a Clerk notebook, for a self-contained learning experience. 
- Clerk has become a well established tool that I and several of m'colleagues will feel comfortable recommending to newcomers.
- Learners can legitimately continue to use it in their *own* day-to-day work (if not introduce to their org / team).
- We can give visibility to more dev tool builders of the Clojure ecosystem. (Klipse is great as a standalone live tutorial, but not so much for daily-drive self-use).
- Importantly, adding Clerk support will preserve backward and forward compatibility with the extant way of using an IDE.
